### ISSUE TITLE
No issues are labelled in private repository

### ISSUE THREAD

**Issue by laurent-radoux** [gh-bot/fix-labeler#5]
I'm relatively new to GitHub and its "actions" feature but I cannot seem to make this one working.

I have tried to add this (very promising) action to a **private** repository in a branch.
I then created a dummy issue, changed some file and committed to this branch using the "fixes #..." keyword in the commit message, without any success.
I can see that there issue is correctly linked to that particular commit but the label is not added.

Reverting to v1.2.1 allowed me to assess that the label is indeed correctly found, so this should not be the root cause.
When I look at the action log, it seems that no issue to be labelled was found.

Is there something I did wrong?
Can this action work for private repository?

I have not tried it in a public repo yet.

**Comment by ENikS** [comment]
It might not work in private repositories right now, try it on public repo

Check out UnityContainer/abstractions  repo for working config
